apiVersion: v1
kind: ServiceAccount
metadata:
  name: zalando-postgres-operator

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: zalando-postgres-operator
rules:
- apiGroups:
  - acid.zalan.do
  resources:
  - postgresqls
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - pods
  - services
  - statefulsets
  - persistentvolumeclaims
  - secrets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zalando-postgres-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zalando-postgres-operator
subjects:
- kind: ServiceAccount
  name: zalando-postgres-operator
